name: Collect

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */3 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # 使用 Python 3.12

    - name: Install dependencies
      run: |
        pip3 install pyYAML
        pip3 install tqdm
        pip3 install geoip2
        pip3 install python-dotenv tqdm

    - name: Execute Python script
      run: python -u subscribe/collect.py -s

    - name: Check script execution
      run: |
        if [ $? -ne 0 ]; then
          echo "Python script failed to execute."
          exit 1
        fi

    - name: Setup Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git config core.ignorecase false

    - name: Pull latest changes
      run: git pull origin main --rebase --autostash

    - name: Commit and Push Changes
      run: |
        git add .
        git diff --staged --quiet || git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S') by GitHub Action"
        git push origin main
