name: Fetch Telegram Links

on:
  workflow_dispatch:

jobs:
  fetch-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install selenium

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install ChromeDriver
        run: |
          unzip -j drivers/chromedriver-linux64.zip -d drivers/
          sudo mv drivers/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run script
        run: python fetch_telegram_links.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update ji.txt with latest links"
          file_pattern: data/ji.txt
